config/routes.rb
LogBhumi::Application.routes.draw do
  devise_for :volunteers, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :volunteers do
    collection do
      get 'update_centers'
      get 'center_redirect'
    end
  end
  resources :volunteer_attendances
  resources :student_attendances

  resources :centers do
    resources :bhumi_classes
  end

  resources :bhumi_classes do
    resources :volunteer_attendances
    resources :student_attendances
  end
  
  get 'volunteers/update_centers', :as => 'update_centers'
  get 'volunteers/center_redirect', :as => 'center_redirect'
  match 'bhumi_classes/update_sub_chapters/:id', :controller=>'bhumi_classes', :action => 'update_sub_chapters'

  authenticated :volunteer do
  	root :to => 'centers#show'
  end
  root :to => 'sessions#new'

end

app/controllers/bhumi_classes_controller.rb
class BhumiClassesController < ApplicationController
	before_filter :auth_user
	# before_filter :vol_allowed
	def create
		@center = Center.find(params[:center_id])
		@chapters = Chapter.all.collect{|c| c.name}
		@sub_chapters = SubChapter.all.collect{|s| s.name}

		unless (@center.bhumi_classes.find_by_date(params[:bhumi_class][:date])!= nil)
			if (params[:bhumi_class][:date].to_date.strftime("%A").downcase == 'saturday' || params[:bhumi_class][:date].to_date.strftime("%A").downcase == 'sunday')
				@class = @center.bhumi_classes.create(:date => params[:bhumi_class][:date], :day_of_week => params[:bhumi_class][:date].to_date.strftime("%A"),:no_of_systems => params[:bhumi_class][:no_of_systems],
													:conducted_status => params[:bhumi_class][:conducted_status], :chapter_taught => params[:bhumi_class][:chapter_taught],
													:sub_chapter_taught => params[:bhumi_class][:sub_chapter_taught], :reason_for_cancellation => params[:bhumi_class][:reason_for_cancellation],
													:comment => params[:bhumi_class][:comment], :filled_by => params[:bhumi_class][:filled_by])


				if @class.save
					UserMailer.class_completion_email(@class).deliver
					if (params[:bhumi_class][:conducted_status] == "0")
						flash.notice = "Successfully updated"
						redirect_to @center
					else
						flash.notice = "Successfully updated"
						redirect_to @class
						@class.send_attendance_reminder
					end
				else
					redirect_to :back
				end
			else
				flash.alert = "Selected date is not a weekend"
				redirect_to :back
			end
		else
			@conducted_class ||= @center.bhumi_classes.where('date = (?) AND conducted_status = (?)',params[:bhumi_class][:date],1)
			@cancelled_class ||= @center.bhumi_classes.where('date = (?) AND conducted_status = (?)',params[:bhumi_class][:date],0)
			if (@conducted_class.count!=0 || @cancelled_class!=0)
				if(@conducted_class.count!=0)
					redirect_to bhumi_class_path(@conducted_class.first.id, :count=>@conducted_class.count)
				else #if(@cancelled_class!=0)
					redirect_to bhumi_class_path(@cancelled_class.first.id, :count=>@cancelled_class.count)
				end
			end
		end
	end

	def show
		if params[:id]
		@class = BhumiClass.find(params[:id])
		else
		@class = current_class		
		end

		if params[:count]
                @count = params[:count]
                else
                @count = ""
                end

		@center = @class.center
                @volunteers = Volunteer.center_vols(@center.id)
                @students = Student.center_students(@center.id)
	end	

	def update_sub_chapters
		@center = Center.find(params[:center])
                subchapter = SubChapter.where(:chapter_id=>params[:id]) unless params[:id].blank?
                render :partial => "bhumi_classes/sub_chapters", :locals => { :subchapter => subchapter}
    	end

end

app/helpers/bhumi_classes_helper.rb
module BhumiClassesHelper
end

app/views/bhumi_classes/_form.html.erb
<div class="well">
  <%= form_for([@center, @center.bhumi_classes.build]) do |f| %>
    <div>
      <%= f.label :date %>
      <%= f.text_field 'date', 'data-behaviour' =>'datepicker'%> <br/>

      <%= f.hidden_field 'filled_by', :value =>current_volunteer.id %>

      <%= f.label :conducted_status %>
      <div id="status-dropdown">
        <%= f.select 'conducted_status', options_for_select({ "Conducted" => 1, "Cancelled" => 0 }), :prompt => "Select" %> <br/>
      </div>
      <div id="class_details" style="display:none">
        <%= f.label :chapter_taught %>
        <%= f.select 'chapter_taught', options_for_select(Chapter.all.collect{|c| [c.name,c.id]}).html_safe, { :include_blank => "Select"}  %><br />
        
	<div id="subchaptersDiv">
        <%= f.label :sub_chapter_taught %>
        <%= render :partial => '/bhumi_classes/sub_chapters' , :locals => { :subchapter => ""} %>
        </div>

        <%= f.label :no_of_systems %>
        <%= f.text_field 'no_of_systems'%> <br/>


      </div>

      <div id="cancellation_details" style="display:none" >
        <%= f.label :reason_for_cancellation %> 
        <%= f.select 'reason_for_cancellation', options_for_select(["Volunteer Related", "Kids Related", "Center Related", "Systems Related", "External Reasons" ]).html_safe, { :include_blank => "Select" } %> <br/>
      </div>

      <%= f.label :comment %>
      <%= f.text_field 'comment'%> <br/>


    <div>
      <%= f.submit "Save", :id => "class-submit", :class => "btn btn-success", :confirm => "Are you sure to submit? Once submitted, you cannot edit the class details"%>
    </div>
    <div class = "errors" style="top:100%;left:42%"</div>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('[data-behaviour~=datepicker]').datepicker({
	     format: 'yyyy-mm-dd',
	     beforeShowDay: onlyWeekends
	   });

   function onlyWeekends(date) {
    var day = date.getDay();
    var today = new Date();
        if(date <= today) {
           if(day == 0 || day == 6) {
             return true;
           } else {
           return false;
           }
        }
        else {
                return false;
        }
  }

  $("#bhumi_class_conducted_status").on('change', function(){
    var status = $(this).val();
    if(status == 0) {
      $("#class_details").hide();
      $("#cancellation_details").show();
    } else {
      $("#cancellation_details").hide();
      $("#class_details").show();
    }
  });

  $("#bhumi_class_date").on('changeDate',function(){
	  $("#bhumi_class_date").datepicker('hide');
  });

  $("#class-submit").click(function(e) {
      var is_valid = true;
      var error_messages = "";
      date = $("#bhumi_class_date");
      var selected_date = new Date($("#bhumi_class_date").val())
      var today = new Date;
      selected_date.setHours(0,0,0,0);
      today.setHours(0,0,0,0);
      if (date.val()==null || date.val()=="") {
        date.addClass('error-border');
        error_messages += "<li>Date is required</li>"
        is_valid = false;
      } else if(selected_date > today) {
        date.addClass('error-border');
        error_messages += "<li>Date should not be a future date</li>"
        is_valid = false;
      } else {
        date.removeClass('error-border');
      }
      var status = $("#bhumi_class_conducted_status");
      if(status.val() == "") {
        status.addClass("error-border");
        error_messages += "<li>Conducted Status is required</li>"
        is_valid = false;
      } else {
        status.removeClass('error-border');
      }

      var systems = $("#bhumi_class_no_of_systems");
      if( $("#bhumi_class_conducted_status").val()==1) {
        if(systems.val()=="" || systems.val()== null) {
          systems.addClass('error-border');
          error_messages += "<li>No. of systems is required</li>"
          is_valid = false;
        } else if(!($.isNumeric(systems.val()))) {
         systems.addClass('error-border');
         error_messages += "<li>No. of systems should be an integer</li>"
         is_valid = false;
        } else {
         systems.removeClass('error-border');
        }
      }
      if (is_valid == false) {
      $('.errors').html("<ul>" + error_messages + "</ul>");
        $('.errors').show();
        e.preventDefault();
        return false;
      } else {
        return true;
    }
    });

    $("#bhumi_class_chapter_taught").change(function() {
    var chapter = $('select#bhumi_class_chapter_taught :selected').val();
    cen="<%= @center.id %>";
    if(chapter == "") chapter="0";
     $.get('/bhumi_classes/update_sub_chapters/' + chapter, { center: cen}, function(data){
        $("#subchaptersDiv").html(data);
    })
    return false;
    });

});
</script>

app/views/bhumi_classes/_student_attendance_modal.html.erb
<div id="studentModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h3 id="myModalLabel">Student Attendance</h3>
  </div>
  <div class="modal-body">
    <%= form_tag(student_attendances_path, :method => :post) do %>
      <table id="student-table" class="table table-hover" style = "margin:30px;">
        <% @students.each_with_index do |s,i| %>
          <tr>
            <td><%= s.full_name %></td>
            <%= hidden_field_tag "student_attendances[#{i}][student_id]", s.id %>
            <%= hidden_field_tag "student_attendances[#{i}][bhumi_class_id]", @class.id %>
            <td>
              <%= radio_button_tag "student_attendances[#{i}][attendance_status]", 'P' %> &nbsp; Present &nbsp;
              <%= radio_button_tag "student_attendances[#{i}][attendance_status]", 'A',:checked => true %> &nbsp; Absent &nbsp;
              
              <br/>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <%= submit_tag "Save" ,:id => "student_attendance_save", :class => "btn btn-success" , :style => "margin:30px;",:confirm => "Are you sure to submit? Once submitted, you cannot edit the attendance details"%>
    <%= button_tag "Cancel" ,:id => "student_attendance_cancel", 'data-dismiss' => "modal",:class => "btn btn-danger" %>
  <% end %>
</div>

app/views/bhumi_classes/_sub_chapters.html.erb
<%= form_for([@center, @center.bhumi_classes.build])  do |form| %>
<% if !subchapter.blank? %>
<%= form.label :sub_chapter_taught %>
<%= form.select 'sub_chapter_taught', options_for_select(subchapter.collect{|s| [s.name,s.id]}).html_safe, { :include_blank => "Select" } %>
<% else %>
<%= form.select 'sub_chapter_taught', options_for_select([]).html_safe, { :include_blank => "Select" } %>
<% end %>
<% end %>

app/views/bhumi_classes/_volunteer_attendance_modal.html.erb
<div id="volunteerModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h3 id="myModalLabel">Volunteer Attendance</h3>
  </div>
  <div class="modal-body">
    <%= form_tag(volunteer_attendances_path, :method => :post) do %>
      <table id="volunteer-table" class="table table-hover" style = "margin:30px;">
        <% @volunteers.each_with_index do |v,i| %>
          <tr>
            <td><%= v.full_name %></td>
            <%= hidden_field_tag "volunteer_attendances[#{i}][volunteer_id]", v.id %>
            <%= hidden_field_tag "volunteer_attendances[#{i}][bhumi_class_id]", @class.id %>
            <td>
              <%= radio_button_tag "volunteer_attendances[#{i}][attendance_status]", 'P' %> &nbsp; Present &nbsp;
              <%= radio_button_tag "volunteer_attendances[#{i}][attendance_status]", 'A',:checked => true  %> &nbsp; Absent &nbsp;
              <%= radio_button_tag "volunteer_attendances[#{i}][attendance_status]", 'L' %> &nbsp; Leave &nbsp; 
              <%= radio_button_tag "volunteer_attendances[#{i}][attendance_status]", 'NA' %> &nbsp; NA &nbsp;
              <br/>
            </td>
          </tr>
        <% end %>
      </table>
  </div>
    <%= submit_tag "Save" ,:id => "volunteer_attendance_save", :class => "btn btn-success" , :style => "margin:30px;" ,:confirm => "Are you sure to submit? Once submitted, you cannot edit the attendance details"%>
    <%= button_tag "Cancel" ,:id => "student_attendance_cancel", 'data-dismiss' => "modal",:class => "btn btn-danger"%>
    <% end %>
</div>

app/views/bhumi_classes/show.html.erb
<% if @count!="" %>
<% flash.notice="The log for this date has already been recorded" %>
<% end %>
<% if @class.conducted_status == true %>
<% if @class.volunteer_attendances.count == 0 || @class.student_attendances.count == 0 %>
<% flash.alert="Please Fill the Attendance" %>
<% end %>
<%if @class.volunteer_attendances.count == 0 %>
	<%= link_to('Add Volunteer Attendance','#volunteerModal', "data-toggle" => "modal", :class => 'btn btn-primary') %>
<% end %>
<%if @class.student_attendances.count == 0 %> 
	<%= link_to('Add Students Attendance','#studentModal', "data-toggle" => "modal", :class => 'btn btn-primary') %>
<% end %>
<% end %>
<br/><br/>
<%= render :partial => "bhumi_classes/volunteer_attendance_modal" %>
<%= render :partial => "bhumi_classes/student_attendance_modal" %>
<h3> Class Details </h3>
<div id="class-details" class="well">
	<p> <b> Date: </b> <%= @class.date %> </p>
	<p> <b> Day: </b> <%= @class.day_of_week %> </p>
	<p> <b> Conducted Status: </b><% if @class.conducted_status == true %>Yes<% else %>No<% end %></p>
	<%if @class.conducted_status == true %>
		<p> <b> Chapter: </b> <%= Chapter.where(:id=>@class.chapter_taught)[0].name %> </p>
	        <p> <b> Sub Chapter: </b> <%= SubChapter.where(:id=>@class.sub_chapter_taught)[0].name %> </p>
		<p> <b> No. of systems: </b> <%= @class.no_of_systems %> </p>
	<% else %>
		<p> <b> Reason for cancellation: </b> <%= @class.reason_for_cancellation %> </p>
	<% end %>
</div>

<h3> Volunteer Attendance </h3>
<table class="table table-hover" style = "margin:30px;">
	<% @class.volunteer_attendances.all.each do |v| %>
	<tr>
		<td> <%= v.volunteer.full_name %> </td>
		<td> <%= v.attendance_status %> </td>
	</tr>
	<% end %>
</table>


<h3> Student Attendance </h3>
<table class="table table-hover" style = "margin:30px;">
	<% @class.student_attendances.all.each do |v| %>
	<tr>
		<td> <%= v.student.full_name %> </td>
		<td> <%= v.attendance_status %> </td>
	</tr>
	<% end %>
</table>