config/routes.rb
LogBhumi::Application.routes.draw do
  devise_for :volunteers, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :volunteers do
    collection do
      get 'update_centers'
      get 'center_redirect'
    end
  end
  resources :volunteer_attendances
  resources :student_attendances

  resources :centers do
    resources :bhumi_classes
  end

  resources :bhumi_classes do
    resources :volunteer_attendances
    resources :student_attendances
  end
  
  get 'volunteers/update_centers', :as => 'update_centers'
  get 'volunteers/center_redirect', :as => 'center_redirect'
  match 'bhumi_classes/update_sub_chapters/:id', :controller=>'bhumi_classes', :action => 'update_sub_chapters'

  authenticated :volunteer do
  	root :to => 'centers#show'
  end
  root :to => 'sessions#new'

end

app/models/bhumi_class.rb
class BhumiClass < ActiveRecord::Base
	has_many :volunteer_attendances
  	has_many :volunteers, :through => :volunteer_attendances
  	has_many :student_attendances
	has_many :students, :through => :student_attendances
	belongs_to :center
	has_many :chapters
	has_many :sub_chapters
	attr_accessible :chapter_taught, :comment, :conducted_status, :date, :day_of_week, :no_of_students, :no_of_systems, :no_of_volunteers, :reason_for_cancellation, :sub_chapter_taught, :filled_by

	def when_to_remind
		self.created_at + 2.days
	end

	def send_attendance_reminder
		if(VolunteerAttendance.where(:bhumi_class_id => self.id).empty?) || 
			(StudentAttendance.where(:bhumi_class_id => self.id).empty?)
			UserMailer.attendance_reminder_email(self).deliver
		end
	end
	handle_asynchronously :send_attendance_reminder, :run_at => Proc.new {|i| i.when_to_remind} 
end

app/models/center.rb
class Center < ActiveRecord::Base
	has_many :students
	has_many :volunteers
	belongs_to :zone
	has_many :bhumi_classes
	attr_accessible :address_line_1, :address_line_2, :cc_name, :city, :day_of_week, :name, :saturday_bc_name, :state, :sunday_bc_name, :zc_name, :zone_name

	def saturday_filling_status
		unless self.day_of_week == "sunday"
			unless self.bhumi_classes.find_by_date(Date.today.beginning_of_week(:saturday)).nil?
				return "Filled"
			else
				return "Not Filled"
			end
		else
			return "NA"
		end
	end

	def sunday_filling_status
		unless self.day_of_week == "saturday"
			unless self.bhumi_classes.find_by_date(Date.today.beginning_of_week(:sunday)).nil?
				return "Filled"
			else
				return "Not Filled"
			end
		else
			return "NA"
		end
	end

	def mailing_list
		recipients_array = []
		recipients_array.push(self.cc_id,self.saturday_bc_id,self.sunday_bc_id,self.zc_id).uniq()
		recipients_email = Volunteer.where(:id => recipients_array).pluck(:email)
	end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :bhumi_class
	attr_accessible :name, :no_of_hours_required
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :center
	has_many :student_attendances
  	has_many :bhumi_classes, :through => :student_attendances
  	attr_accessible :center, :date_of_birth, :first_name, :last_name, :no_of_classes_absent, :no_of_classes_present, :school, :standard

  	def self.center_students(c_id)
    	self.where(:center_id => c_id )
  	end

	def full_name
    		"#{first_name} #{last_name}"
  	end
end

app/models/student_attendance.rb
class StudentAttendance < ActiveRecord::Base
	belongs_to :student 
	belongs_to :bhumi_class
  	attr_accessible :student_id, :bhumi_class_id , :attendance_status
  # attr_accessible :title, :body
end

app/models/sub_chapter.rb
class SubChapter < ActiveRecord::Base
	belongs_to :chapter
  	attr_accessible :name, :number, :chapter_id
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauth_providers => [:google_oauth2]

  belongs_to :center
  has_many :volunteer_attendances
  has_many :bhumi_classes, :through => :volunteer_attendances
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, 
  				  :first_name, :last_name, :mobile, :date_of_birth, 
  				  :date_of_joining, :center, :no_of_classes_present, 
  				  :no_of_classes_absent, :no_of_leaves, :status, :function, 
  				  :day_of_week, :is_admin, :kpi_member, :hr_member, 
  				  :zone_coordinator, :center_coordinator,:batch_coordinator

  # attr_accessible :title, :body

  def self.from_omniauth(auth)
    if volunteer = Volunteer.find_by_email(auth.info.email)
      volunteer.provider = auth.provider
#      volunteer.email = auth.auth
      volunteer
    #else
    #  where(auth.slice(:provider, :email)).first_or_create do |volunteer|
    #    volunteer.provider = auth.provider
        # volunteer.name = auth.info.name
    #    volunteer.email = auth.info.email
    #  end
    end
  end

  def self.center_vols(c_id)
    self.where(:center_id => c_id )
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def check_position
    self.batch_coordinator == true || self.zone_coordinator == true || self.center_coordinator == true || self.kpi_member == true
  end

  def self.send_reminder
    UserMailer.reminder_email.deliver
  end

  def self.mail_recipients
    Volunteer.where("center_coordinator = ?  OR batch_coordinator =? ",1,1).pluck(:email)
  end
end

app/models/volunteer_attendance.rb
class VolunteerAttendance < ActiveRecord::Base
	belongs_to :volunteer 
	belongs_to :bhumi_class
  	attr_accessible :volunteer_id, :bhumi_class_id , :attendance_status
end

app/models/zone.rb
class Zone < ActiveRecord::Base
	has_many :centers
  	attr_accessible :name, :zc_name, :city
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
	before_filter :auth_user
	before_filter :auth_center
	def show
		if params[:id]
			@center = Center.find(params[:id])
		else
			@center = current_center
		end
	end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bhumi_classes_helper.rb
module BhumiClassesHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav pull-right">
  <% if volunteer_signed_in? %>
    <li>
    	
    	<%= link_to('Create New Class', center_path(current_volunteer.center.id), :method=>'get', :style=>"font-weight:bold; float:left") %>
    	<%= link_to('Logout', destroy_volunteer_session_path, :method=>'delete', :style=>"font-weight:bold ;float:left") %>
    </li>
  <% else %>
    <li>
    	<%= link_to('Login', volunteer_omniauth_authorize_path(:google_oauth2), :style=>"font-weight:bold" )  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Kanini Log" %></title>
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
    <h1><a href="#" style="float:left; position:absolute;top:33%">Kanini Log</a></h1>
    <a href="https://www.bhumi.org.in" target="_blank">
      <img id="bhumi-logo" src="/bhumi_logo.jpg" alt="Bhumi Logo" style="float:right"/>
    </a>
      <div style="clear:both"></div>
    <header class="navbar">
      <nav class="navbar-inner">
          <%= render 'layouts/navigation' %>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
   </dev>
</body>
</html>